import {spawn,spawnSync} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const host='127.0.0.1',previewPort=4173,debuggingPort=9222,appUrl=`http://${host}:${previewPort}/`,delay=ms=>new Promise(r=>setTimeout(r,ms));
function assert(c,m){if(!c)throw new Error(m)}
function findChrome(){for(const c of [process.env.CHROME_BIN,'google-chrome','google-chrome-stable','chromium','chromium-browser'].filter(Boolean)){if(c.includes('/'))return c;const f=spawnSync('which',[c],{encoding:'utf8'});if(f.status===0&&f.stdout.trim())return f.stdout.trim()}throw new Error('CHROME_NOT_FOUND')}
async function stopChild(c){if(!c||c.exitCode!==null)return;const e=new Promise(r=>c.once('exit',r));c.kill('SIGTERM');await Promise.race([e,delay(2000)]);if(c.exitCode===null)c.kill('SIGKILL')}
async function waitForHttp(url,t=20000){const d=Date.now()+t;while(Date.now()<d){try{const r=await fetch(url,{cache:'no-store'});if(r.ok)return r}catch{}await delay(100)}throw new Error(`HTTP_TIMEOUT:${url}`)}
class CdpClient{constructor(s){this.socket=s;this.nextId=1;this.pending=new Map();this.listeners=new Map();s.addEventListener('message',e=>{let m;try{m=JSON.parse(typeof e.data==='string'?e.data:String(e.data))}catch{return}if(m.id){const p=this.pending.get(m.id);if(!p)return;this.pending.delete(m.id);m.error?p.reject(new Error(`${m.error.code}:${m.error.message}`)):p.resolve(m.result??{});return}for(const l of this.listeners.get(m.method)??[])l(m.params??{})});}static async connect(url){const s=new WebSocket(url);await new Promise((r,j)=>{s.addEventListener('open',r,{once:true});s.addEventListener('error',()=>j(new Error('CDP_CONNECT_ERROR')),{once:true})});return new CdpClient(s)}on(m,l){const a=this.listeners.get(m)??[];a.push(l);this.listeners.set(m,a)}send(method,params={}){const id=this.nextId++;return new Promise((resolve,reject)=>{this.pending.set(id,{resolve,reject});this.socket.send(JSON.stringify({id,method,params}))})}close(){this.socket.close()}}
async function evaluate(c,e){const r=await c.send('Runtime.evaluate',{expression:e,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description??r.exceptionDetails.text);return r.result?.value}
async function waitFor(c,e,l,t=10000){const d=Date.now()+t;while(Date.now()<d){try{if(await evaluate(c,`Boolean(${e})`))return}catch{}await delay(50)}throw new Error(`BROWSER_WAIT_TIMEOUT:${l}`)}
async function navigate(c,v){await c.send('Emulation.setDeviceMetricsOverride',{width:v.width,height:v.height,deviceScaleFactor:1,mobile:v.mobile});await c.send('Page.navigate',{url:`${appUrl}?smoke=${Date.now()}`});await waitFor(c,`document.readyState==='complete'&&document.querySelectorAll('.menu button').length===3`,'menu');assert(await evaluate(c,`document.documentElement.scrollWidth<=window.innerWidth+1`),`${v.name}:horizontal overflow`);assert(await evaluate(c,`Math.abs(document.querySelector('.ad-bar').getBoundingClientRect().bottom-window.innerHeight)<=1`),`${v.name}:ad bottom`)}
async function startMode(c,mode,order='sente',senteHandicap='even',goteHandicap='even'){await evaluate(c,`document.querySelector('#start').click()`);await waitFor(c,`document.querySelector('[data-mode="${mode}"]')`,'mode');await evaluate(c,`document.querySelector('[data-mode="${mode}"]').click()`);await waitFor(c,`document.querySelector('#go')&&document.querySelector('#senteHandicap')&&document.querySelector('#goteHandicap')`,'settings');assert(await evaluate(c,`document.querySelector('#order').value==='random'`),'random default missing');assert(await evaluate(c,`!document.querySelector('#handicapSide')`),'obsolete handicap-side selector remains');await evaluate(c,`(()=>{document.querySelector('#order').value=${JSON.stringify(order)};document.querySelector('#senteHandicap').value=${JSON.stringify(senteHandicap)};document.querySelector('#goteHandicap').value=${JSON.stringify(goteHandicap)};document.querySelector('#go').click();})()`);await waitFor(c,`document.querySelectorAll('.board .cell').length===81`,'board')}
async function moveFirstPawn(c){await evaluate(c,`document.querySelectorAll('.board .cell')[54].click()`);await waitFor(c,`document.querySelectorAll('.board .cell')[45].classList.contains('legal')`,'pawn target');await evaluate(c,`document.querySelectorAll('.board .cell')[45].click()`)}
const chromePath=findChrome(),profile=await mkdtemp(join(tmpdir(),'shogi-browser-smoke-'));let preview,chrome,cdp;const errors=[];
try{preview=spawn(process.platform==='win32'?'npm.cmd':'npm',['run','preview','--','--host',host,'--port',String(previewPort),'--strictPort'],{stdio:['ignore','pipe','pipe'],env:{...process.env}});await waitForHttp(appUrl);chrome=spawn(chromePath,['--headless=new','--disable-gpu','--disable-dev-shm-usage','--disable-background-networking','--no-first-run','--no-default-browser-check','--no-sandbox',`--remote-debugging-address=${host}`,`--remote-debugging-port=${debuggingPort}`,`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','pipe','pipe']});await waitForHttp(`http://${host}:${debuggingPort}/json/version`);const targets=await (await waitForHttp(`http://${host}:${debuggingPort}/json/list`)).json(),page=targets.find(t=>t.type==='page'&&t.webSocketDebuggerUrl);assert(page,'CDP_PAGE_TARGET_NOT_FOUND');cdp=await CdpClient.connect(page.webSocketDebuggerUrl);cdp.on('Runtime.exceptionThrown',p=>errors.push(p.exceptionDetails?.exception?.description??p.exceptionDetails?.text));await cdp.send('Page.enable');await cdp.send('Runtime.enable');
await navigate(cdp,{name:'desktop',width:1280,height:800,mobile:false});assert(await evaluate(cdp,`[...document.querySelectorAll('.menu button')].map(x=>x.textContent).join('|')==='スタート|ルール|設定'`),'menu labels');await evaluate(cdp,`document.querySelector('#rules').click()`);await waitFor(cdp,`document.querySelector('.rules-document')`,'rules');for(const t of ['二歩','打ち歩詰め','千日手','入玉・持将棋','投了','先手・後手'])assert(await evaluate(cdp,`document.querySelector('.rules-document').textContent.includes(${JSON.stringify(t)})`),`rules:${t}`);await evaluate(cdp,`document.querySelector('#back').click()`);await waitFor(cdp,`document.querySelector('.menu')`,'rules back');await evaluate(cdp,`document.querySelector('#start').click()`);await waitFor(cdp,`document.querySelector('[data-mode="cpu"]')`,'mode');await evaluate(cdp,`document.querySelector('[data-mode="cpu"]').click()`);await waitFor(cdp,`document.querySelector('#go')`,'settings');assert(await evaluate(cdp,`document.querySelector('#senteHandicap')&&document.querySelector('#goteHandicap')`),'dual handicap settings missing');await evaluate(cdp,`document.querySelector('#back').click()`);await waitFor(cdp,`document.querySelector('[data-mode="cpu"]')`,'hierarchy');assert(await evaluate(cdp,`!document.querySelector('.menu')`),'back jumped home');await cdp.send('Page.navigate',{url:`${appUrl}?dual=${Date.now()}`});await waitFor(cdp,`document.querySelector('.menu')`,'dual menu');await startMode(cdp,'local','sente','two','bishop');assert(await evaluate(cdp,`(()=>{const cells=[...document.querySelectorAll('.board .cell')];const senteRook=cells[70]?.textContent;const senteBishop=cells[64]?.textContent;const goteRook=cells[16]?.textContent;const goteBishop=cells[10]?.textContent;return senteRook===''&&senteBishop===''&&goteRook==='飛'&&goteBishop==='';})()`),'dual handicap board mismatch');await cdp.send('Page.navigate',{url:`${appUrl}?local=${Date.now()}`});await waitFor(cdp,`document.querySelector('.menu')`,'fresh');await startMode(cdp,'local');await moveFirstPawn(cdp);await waitFor(cdp,`document.querySelector('.match-header>strong').textContent.includes('後手番')`,'local move');
await cdp.send('Page.navigate',{url:`${appUrl}?cpu=${Date.now()}`});await waitFor(cdp,`document.querySelector('.menu')`,'cpu menu');await startMode(cdp,'cpu');await moveFirstPawn(cdp);await waitFor(cdp,`document.querySelector('.match-header>strong').textContent.includes('先手番')`,'cpu reply',20000);
await navigate(cdp,{name:'mobile',width:390,height:844,mobile:true});await startMode(cdp,'local');assert(await evaluate(cdp,`document.querySelector('#elapsed').textContent!=='--:--'`),'elapsed');await evaluate(cdp,`document.querySelector('#resign').click()`);await waitFor(cdp,`document.querySelector('#resignNo')`,'resign dialog');await evaluate(cdp,`document.querySelector('#resignNo').click()`);await waitFor(cdp,`!document.querySelector('.resign-dialog')`,'resign cancel');await evaluate(cdp,`document.querySelector('#resign').click()`);await waitFor(cdp,`document.querySelector('#resignYes')`,'resign yes');await evaluate(cdp,`document.querySelector('#resignYes').click()`);await waitFor(cdp,`document.querySelector('.result-panel')`,'result');const result=await evaluate(cdp,`document.querySelector('.result-panel').textContent`);assert(result.includes('勝利')&&result.includes('敗北'),'victory defeat');assert(await evaluate(cdp,`[...document.querySelectorAll('.result-actions button')].map(x=>x.textContent).join('|')==='もう一度対戦する|同じルールでもう一度対戦する|ホームに戻る'`),'result actions');assert(await evaluate(cdp,`document.documentElement.scrollWidth<=window.innerWidth+1`),'mobile overflow');assert(errors.length===0,`browser errors:${errors.join('\n')}`);console.log(JSON.stringify({ok:true,desktop:true,mobile:true,dualHandicaps:true,localMove:true,cpuWorker:true,resignation:true,backHierarchy:true,adBar:true}));}finally{cdp?.close();await stopChild(chrome);await stopChild(preview);await rm(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100})}