import './style.css';
import { applyMove, initialPosition, isCheck, isMate, legalMoves } from './game/engine';
import type { Handicap, Move, PieceKind, Position } from './game/types';

const names:Record<string,string>={king:'玉',rook:'飛',bishop:'角',gold:'金',silver:'銀',knight:'桂',lance:'香',pawn:'歩',dragon:'龍',horse:'馬',promotedSilver:'全',promotedKnight:'圭',promotedLance:'杏',tokin:'と'};
let pos:Position=initialPosition(); let selected:[number,number]|null=null; let hand:PieceKind|null=null; let candidates:Move[]=[];
const app=document.querySelector<HTMLDivElement>('#app')!;
function menu(){app.innerHTML=`<main class="menu"><h1>将棋</h1><button id="start">スタート</button><button id="rules">ルール</button><button id="settings">設定</button></main>`;document.querySelector('#start')!.addEventListener('click',mode);document.querySelector('#rules')!.addEventListener('click',rules);document.querySelector('#settings')!.addEventListener('click',settings);}
function back(){return `<button class="back" id="back">← 戻る</button>`} function bindBack(){document.querySelector('#back')?.addEventListener('click',menu)}
function mode(){app.innerHTML=`<main class="panel">${back()}<h2>ゲームモード</h2><button data-mode="cpu">CPU対局</button><button data-mode="local">ローカル2人対局</button><button data-mode="online">オンライン対局</button></main>`;bindBack();document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>settingsGame((b as HTMLElement).dataset.mode!)));}
function settingsGame(mode:string){app.innerHTML=`<main class="panel">${back()}<h2>ゲーム設定</h2>${mode==='cpu'?`<label>CPU難易度<select><option>初心者</option><option>中級者</option><option>アマチュア</option><option>プロ</option><option>タイトル級</option></select></label>`:''}<label>駒落ち<select id="handicap"><option value="even">平手</option><option value="rook">飛車落ち</option><option value="bishop">角落ち</option><option value="two">2枚落ち</option><option value="four">4枚落ち</option><option value="six">6枚落ち</option></select></label><button id="go">開始</button><p class="note">${mode==='online'?'オンライン接続はシステム側実装後に有効化します。':''}</p></main>`;bindBack();document.querySelector('#go')!.addEventListener('click',()=>{pos=initialPosition((document.querySelector('#handicap') as HTMLSelectElement).value as Handicap);play();});}
function rules(){app.innerHTML=`<main class="document">${back()}<h2>ルール</h2><p>9×9の盤で、相手の玉を詰ませることが目的です。取った駒は持ち駒として自分の手番に打てます。敵陣3段では対象駒を成ることができ、歩・香・桂には行き所がなくなる場合の強制成りがあります。</p><p>二歩、打ち歩詰め、行き所のない駒打ち、自玉を王手にさらす着手、王手放置はできません。合法手のみ盤面に反映されます。</p><p>同一局面4回の千日手、連続王手の千日手、入玉・持将棋等は正式ルールに従う必要があります。入玉・持将棋の具体方式は設計上未確定のため、この版では勝敗を自動確定しません。</p></main>`;bindBack();}
function settings(){app.innerHTML=`<main class="panel">${back()}<h2>設定</h2><label>BGM <input type="checkbox" disabled> ON</label><label>音量 <input type="range" min="0" max="100" value="70"></label><label>SE <input type="checkbox" disabled> ON</label><label>音量 <input type="range" min="0" max="100" value="70"></label><button disabled>利用規約</button><button disabled>クレジット</button><button disabled>ライセンス</button><p class="note">本文・素材は設計上Cloudflare側から後付けする構造です。</p></main>`;bindBack();}
function play(){const moves=legalMoves(pos);const mate=isMate(pos);app.innerHTML=`<main class="game"><header>${back()}<strong>${mate?'詰み':pos.turn==='sente'?'先手番':'後手番'}${isCheck(pos,pos.turn)&&!mate?'・王手':''}</strong></header><section class="hand" id="goteHand"></section><div class="board" id="board"></div><section class="hand" id="senteHand"></section>${mate?`<div class="result">${pos.turn==='sente'?'後手':'先手'}の勝ち</div>`:''}</main>`;bindBack();
 const board=document.querySelector('#board')!;for(let y=0;y<9;y++)for(let x=0;x<9;x++){const q=pos.board[y]![x];const cell=document.createElement('button');cell.className='cell';if(selected?.[0]===y&&selected[1]===x)cell.classList.add('selected');if(candidates.some(m=>m.to[0]===y&&m.to[1]===x))cell.classList.add('legal');if(q){cell.textContent=names[q.kind];if(q.side==='gote')cell.classList.add('gote');}cell.addEventListener('click',()=>clickSquare(y,x,moves));board.append(cell);}renderHand('gote','goteHand',moves);renderHand('sente','senteHand',moves);}
function renderHand(side:'sente'|'gote',id:string,moves:Move[]){const el=document.querySelector(`#${id}`)!;el.innerHTML=`<span>${side==='sente'?'先手':'後手'} 持ち駒</span>`;for(const [kind,n] of Object.entries(pos.hands[side]))if(n>0){const b=document.createElement('button');b.textContent=`${names[kind]}×${n}`;b.disabled=side!==pos.turn;b.addEventListener('click',()=>{selected=null;hand=kind as PieceKind;candidates=moves.filter(m=>m.drop===kind);play();});el.append(b);}}
function clickSquare(y:number,x:number,moves:Move[]){const hit=candidates.filter(m=>m.to[0]===y&&m.to[1]===x);if(hit.length){let m=hit[0]!;if(hit.length===2&&hit.some(v=>v.promote)&&confirm('成りますか？'))m=hit.find(v=>v.promote)!;pos=applyMove(pos,m);selected=null;hand=null;candidates=[];play();return;}const q=pos.board[y]![x];hand=null;if(q?.side===pos.turn){selected=[y,x];candidates=moves.filter(m=>m.from?.[0]===y&&m.from[1]===x);}else{selected=null;candidates=[];}play();}
menu();
